### ISSUE TITLE
Error occurs on Mac OS arm

### ISSUE THREAD

**Issue by Jonathan-Xiao** [picobyte/stable-diffusion-webui-wd14-tagger#18]
When I drag a picture into tagger, the client-end always shows messages like these:

```
Installing onnxruntime
Error completing request
Loading wd14-vit-v2-git model file from SmilingWolf/wd-v1-4-vit-tagger-v2
Arguments: (<PIL.Image.Image image mode=RGB size=1080x1620 at 0x2C6444DC0>, '', False, '', '[name].[output_extension]', 'ignore', False, False, 'wd14-vit-v2-git', 0.35, '', '', False, False, True, '0_0, (o)_(o), +_+, +_-, ._., <o>_<o>, <|>_<|>, =_=, >_<, 3_3, 6_9, >_o, @_@, ^_^, o_o, u_u, x_x, |_|, ||_||', False, False) {}
Traceback (most recent call last):
  File "/Volumes/workspace/github/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/Volumes/workspace/github/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Volumes/workspace/github/stable-diffusion-webui/extensions/tagger/tagger/ui.py", line 69, in on_interrogate
    ratings, tags = interrogator.interrogate(image)
  File "/Volumes/workspace/github/stable-diffusion-webui/extensions/tagger/tagger/interrogator.py", line 275, in interrogate
    self.load()
  File "/Volumes/workspace/github/stable-diffusion-webui/extensions/tagger/tagger/interrogator.py", line 250, in load
    run_pip(f'install {package}', 'onnxruntime')
  File "/Volumes/workspace/github/stable-diffusion-webui/modules/launch_utils.py", line 124, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "/Volumes/workspace/github/stable-diffusion-webui/modules/launch_utils.py", line 101, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install onnxruntime.
Command: "/Volumes/workspace/github/stable-diffusion-webui/venv/bin/python3" -m pip install onnxruntime-gpu --prefer-binary
Error code: 1
stderr: ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu


Traceback (most recent call last):
  File "/Volumes/workspace/github/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Volumes/workspace/github/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Volumes/workspace/github/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/Volumes/workspace/github/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 4, received: 3).
Wanted outputs:
    [textbox, label, label, html]
Received outputs:
    [None, "", "<div class='error'>RuntimeError: Couldn&#x27;t install onnxruntime.
Command: &quot;/Volumes/workspace/github/stable-diffusion-webui/venv/bin/python3&quot; -m pip install onnxruntime-gpu --prefer-binary
Error code: 1
stderr: ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu
</div><div class='performance'><p class='time'>Time taken: <wbr>4.00s</p></div>"]
```

It seems like it doesn't work on the Mac OS arm, any suggestions?

**Comment by picobyte** [comment]
Sorry I completely missed this. It may be that my requirements.txt was wrong. I corrected it, hopefully, then this won't occur again.
