### ISSUE TITLE
An error is reported after clicking the "Interrogate image" button，stable-diffusion-webui v1.4.1 

### ISSUE THREAD

**Issue by wosilusheng** [picobyte/stable-diffusion-webui-wd14-tagger#35]
*** Error completing request
*** Arguments: (<PIL.Image.Image image mode=RGB size=320x320 at 0x44B3202E0>, 'WD14 moat tagger v2', '', '', '', '', '', '') {}
    Traceback (most recent call last):
      File "/Users/lusheng01/code/open/stable-diffusion-webui/modules/call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "/Users/lusheng01/code/open/stable-diffusion-webui/modules/call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "/Users/lusheng01/code/open/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/ui.py", line 103, in on_interrogate_image_submit
        interrogator.interrogate_image(image)
      File "/Users/lusheng01/code/open/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/interrogator.py", line 145, in interrogate_image
        QData.single_data(fi_key)
      File "/Users/lusheng01/code/open/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/uiset.py", line 492, in single_data
        for i, val in map(cls.get_i_wt, lst):
      File "/Users/lusheng01/code/open/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/uiset.py", line 396, in get_i_wt
        raise IndexError(f'Index {i}: out of bounds for query[{qlen}]')
    IndexError: Index 1: out of bounds for query[1]

---
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 6, received: 3).
Wanted outputs:
    [html, html, label, label, label, html]
Received outputs:
    [None, "", "<div class='error'>IndexError: Index 1: out of bounds for query[1]</div><div class='performance'><p class='time'>Time taken: <wbr>0.00s</p></div>"]

**Comment by 1803233552** [comment]
I'm also having this issue, which usually comes up after running it once or twice

**Comment by kuso-ge** [comment]
Same error, 
If you try to interrogate an image you already interrogated before, this error also appears.

**Comment by picobyte** [comment]
It only occurs if you interrogate twice, that code path was not working. I've found the problem but it requires a little more before it produces output on the second interrogation.

**Comment by picobyte** [comment]
This should be fixed. It appears #28 should not have been merged, there were serious limitations that I had not realized. With the single image interrogation this became very clear, in a batch interrogation it was not so obvious. so.. thanks for reporting.

**Comment by 1803233552** [comment]
> It looks like it should be solved now, no error is reported here

**Comment by picobyte** [comment]
Thanks. Please also pick up latest commit, there was an issue with the exclude tags not being excluded in the tags files
