### ISSUE TITLE
Cannot run on windows with error AttributeError: 'Checkbox' object has no attribute 'input'

### ISSUE THREAD

**Issue by ingtellect** [picobyte/stable-diffusion-webui-wd14-tagger#41]
Hi, I just installed this extension and got the following error

```
Create LRU cache (max_size=16) for preprocessor results.
Error executing callback ui_tabs_callback for C:\Users\ingtellect\Documents\repo\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger-1.1.1\scripts\tagger.py
Traceback (most recent call last):
  File "C:\Users\ingtellect\Documents\repo\stable-diffusion-webui\modules\script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Users\ingtellect\Documents\repo\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger-1.1.1\tagger\ui.py", line 394, in on_ui_tabs
    cumulative.input(fn=It.flip('cumulative'), inputs=[], outputs=[])
AttributeError: 'Checkbox' object has no attribute 'input'

```

I tried both 1.1.1 release and the latest commit [5735560](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/commit/57355606b7093237a8d0c995b70be1746c832981)
I am using windows 10 and python 3.10.9

How can I fix this?

**Comment by picobyte** [comment]
probably by upgrading gradio. I don't know where they introduced input, but I don't have this error.

**Comment by WilliamChen-luckbob** [comment]
just run `pip install --upgrade gradio` as maitainer mentioned and pull latest master branch of webui then run again,my problem solved
