### ISSUE TITLE
AUTO1111`s webui dev branch launch error

### ISSUE THREAD

**Issue by rltgjqmcpgjadyd** [picobyte/stable-diffusion-webui-wd14-tagger#45]
after 95821f0132f5437ef30b0dbcac7c51e55818c18f commit
webui.py is split
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/95821f0132f5437ef30b0dbcac7c51e55818c18f

this causes tagger to throw an error

here`s log

*** Error loading script: tagger.py
    Traceback (most recent call last):
      File "J:\SDWebUI\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\SDWebUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\SDWebUI\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py", line 6, in <module>
        from tagger.ui import on_ui_tabs  # pylint: disable=import-error
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\SDWebUI\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py", line 19, in <module>
        from webui import wrap_gradio_gpu_call  # pylint: disable=import-error
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ImportError: cannot import name 'wrap_gradio_gpu_call' from 'webui' (J:\SDWebUI\webui.py)

---

**Comment by Panchovix** [comment]
Can confirm this issue as well

**Comment by RoelKluin** [comment]
Looks good, but will have to come after my work.
