### ISSUE TITLE
when execute webui.bat start sd,  'Checkbox' object has no attribute 'input'

### ISSUE THREAD

**Issue by asleepcat** [picobyte/stable-diffusion-webui-wd14-tagger#58]
Error executing callback ui_tabs_callback for D:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py", line 410, in on_ui_tabs
    cumulative.input(fn=It.flip('cumulative'), inputs=[], outputs=[])
AttributeError: 'Checkbox' object has no attribute 'input'

**Comment by picobyte** [comment]
Your gradio is outdated, there was already an issue about it. you need to install it, make sure you are in your virtual environment if you use one.
