### ISSUE TITLE
When it runs on M1: AttributeError: 'Checkbox' object has no attribute 'input'

### ISSUE THREAD

**Issue by AnnaChen999** [picobyte/stable-diffusion-webui-wd14-tagger#59]
When I open SD on M1, I don't see the tagger in the navigation bar, the terminal always sends me a feedback like this:

Error executing callback ui_tabs_callback for /Users/anna/Documents/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger-1.1.2/scripts/tagger.py
Traceback (most recent call last):
  File "/Users/anna/Documents/sd/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "/Users/anna/Documents/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger-1.1.2/tagger/ui.py", line 410, in on_ui_tabs
    cumulative.input(fn=It.flip('cumulative'), inputs=[], outputs=[])
AttributeError: 'Checkbox' object has no attribute 'input'

**Comment by picobyte** [comment]
come on, learn how to search and don't open another right underneath another. I am not a helpdesk.
