### ISSUE TITLE
getting "Error loading script: tagger.py" on Colab

### ISSUE THREAD

**Issue by kenkenissocool** [picobyte/stable-diffusion-webui-wd14-tagger#87]
Hi! I'm running on Google Colab Pro+ with V100 and I tried to install this fantastic tagger extension via this command. 
```from google.colab import drive
drive.mount('/content/drive')
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
%cd /content/stable-diffusion-webui
%cd extensions
!git clone https://github.com/picobyte/stable-diffusion-webui-wd14-tagger
%cd /content/stable-diffusion-webui
!python launch.py --share --xformers --enable-insecure-extension-access
```

however, even though the tagger extension appears to be installed in the SD webUI's extensions tab, the tagger tab won't show up. I tried restarting and reloading, which showed this log and didn't to any better. I am totally a newbie to this SD thing, and might've missed something, but if anyone has the same issue and hopefully a solution to this, it would be appreciated if you could comment 🙏 

```loading WD14-tagger reqs from /content/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/requirements.txt
Checking WD14-tagger requirements.
Restarting UI...
Closing server running on port: 7860
*** Error loading script: tagger.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/scripts/tagger.py", line 5, in <module>
        from tagger.api import on_app_started  # pylint: disable=import-error
      File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/api.py", line 17, in <module>
        from tagger import utils  # pylint: disable=import-error
      File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/utils.py", line 13, in <module>
        from tagger.interrogator import Interrogator, DeepDanbooruInterrogator, \
      File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/interrogator.py", line 32, in <module>
        if shared.cmd_opts.additional_device_ids is not None:
    AttributeError: 'Namespace' object has no attribute 'additional_device_ids'
```

**Comment by kenkenissocool** [comment]
Oh, I changed on to T4 GPU and it worked.

**Comment by yincangshiwei** [comment]
> Oh, I changed on to T4 GPU and it worked.

Hello, how did you switch to T4 GPU.

**Comment by Zhaoguanjing** [comment]
At line 32, add `setattr(shared.cmd_opts, "additional_device_ids", None)` to the previous line of `if shared.cmd_opts.additional_device_ids is not None`
