### ISSUE TITLE
error when using deepdanbooru to

### ISSUE THREAD

**Issue by grapefruit25** [picobyte/stable-diffusion-webui-wd14-tagger#96]
works fine with WD14 or others as interrogator
error with deepdanbooru-v3-20211112-sgd-e28 or deepdanbooru-v4-20200814-sgd-e30
anyone know how to fix it?
here's the error code

Loading deepdanbooru-v4-20200814-sgd-e30 from <DirEntry 'deepdanbooru-v4-20200814-sgd-e30'>
*** Error completing request
*** Arguments: (<PIL.Image.Image image mode=RGB size=4961x5742 at 0x1BAE0E2B430>, 'deepdanbooru-v4-20200814-sgd-e30', '', '', '', '', '', '') {}
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-new\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "D:\stable-diffusion-webui-new\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\stable-diffusion-webui-new\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py", line 113, in on_interrogate_image_submit
        interrogator.interrogate_image(image)
      File "D:\stable-diffusion-webui-new\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 150, in interrogate_image
        data = ('', '', fi_key) + self.interrogate(image)
      File "D:\stable-diffusion-webui-new\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 302, in interrogate
        self.load()
      File "D:\stable-diffusion-webui-new\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 277, in load
        import deepdanbooru.project as ddp
      File "D:\stable-diffusion-webui-new\venv\lib\site-packages\deepdanbooru\__init__.py", line 8, in <module>
        import deepdanbooru.data
      File "D:\stable-diffusion-webui-new\venv\lib\site-packages\deepdanbooru\data\__init__.py", line 5, in <module>
        import tensorflow_io as tfio
    ModuleNotFoundError: No module named 'tensorflow_io'

---
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-new\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui-new\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\stable-diffusion-webui-new\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "D:\stable-diffusion-webui-new\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (on_interrogate_image_submit) didn't receive enough output values (needed: 7, received: 3).
Wanted outputs:
    [state, html, html, label, label, label, html]
Received outputs:
    [None, "", "<div class='error'>ModuleNotFoundError: No module named &#x27;tensorflow_io&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>0.1 sec.</span></p><p class='vram'><abbr title='Active: peak amount of video memory used during generation (excluding cached data)'>A</abbr>: <span class='measurement'>2.03 GB</span>, <wbr><abbr title='Reserved: total amout of video memory allocated by the Torch library '>R</abbr>: <span class='measurement'>2.04 GB</span>, <wbr><abbr title='System: peak amout of video memory allocated by all running programs, out of total capacity'>Sys</abbr>: <span class='measurement'>3.2/10 GB</span> (32.2%)</p></div>"]

**Comment by jet616** [comment]
the same as u, i think this plugin is damn out.

**Comment by silveroxides** [comment]
> ModuleNotFoundError: No module named 'tensorflow_io'
> Time taken: 0.1 sec.

Open extensions directory, open stable-diffusion-webui-wd14-tagger folder, open the requirements.txt in notepad and add a new line where it says tensorflow_io
